### ISSUE TITLE
[Bug]: Blocks widget isn't synchronized

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1466]
### Describe the bug

The latest update is Nov,  27

### Reproduce

1. Go to 'add widget'
2. Click on '.Block widget'
3. See error

### Operating system

Graphene OS, Iphone, Android

### Bitkit version

v93

**Comment by rbndg** [comment]
This was a backend issues and should be fixed now

**Comment by JeanlChristophe** [comment]
I am reopening the issue, it's still not synchronised. Last block is from yersterday.

**Comment by pwltr** [comment]
It's working for me, maybe you need to wait (~10s) for the widget to sync @JeanlChristophe ? I can check if I can improve the sync time in Bitkit.

**Comment by rbndg** [comment]
I restarted again but I’m gonna check in 24h to see if it’s synced or not

**Comment by rbndg** [comment]
still synced after 24h
