### ISSUE TITLE
[Bug]: Can't receive from Strike

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1554]
### Describe the bug

Sending to Strike is working fine, but not receiving.

### Operating system

iOS 17.4

### Bitkit version

102

**Comment by JeanlChristophe** [comment]
@mattcrv don't use Strike and problem is solved..

1. Is it onchain or offchain payement?
2. What's the error message do you have?

**Comment by mattcrv** [comment]
> don't use Strike and problem is solved..

😂

This actually came from a user who warned me in the the DMs. I tested and could reproduce it, so I opened the issue.

![image](https://github.com/synonymdev/bitkit/assets/93796166/51a2f958-1524-4130-90b3-0803c5c048c7)

> Is it onchain or offchain payment?

LN

> What's the error message do you have?

No error, Strike simply doesn't seem to be able to find a route to Bitkit. This is possibly due to Blocktank being poorly connected, but I can send from Strike to any other wallet except to Bitkit, so it might be a deeper Bitkit issue, dunno.

https://github.com/synonymdev/bitkit/assets/93796166/5da1c0f5-5294-4f11-b193-9fddbd708095

**Comment by coreyphillips** [comment]
I'm able to successfully route from Strike to Bitkit on a daily basis through my own personal LND node.

This would hint at a potential Blocktank liquidity issue with Strike's nodes.

**Comment by JeanlChristophe** [comment]
@rbndg can you have a look about the outbound Liquidity from Blocktank to Strike?

**Comment by rbndg** [comment]
should be fixed

**Comment by mattcrv** [comment]
Still not working here:

![IMG_0226](https://github.com/synonymdev/bitkit/assets/93796166/1ea635f7-716b-4b4b-ad92-7f0900717bee)

**Comment by JeanlChristophe** [comment]
@mattcrv the issue was fix. During the events we paid with Strike users. Closing this ticket but we will soon look about how to automated the liquidity.
